roles:
  loup-1: None
  loup-2: None
  loup-3: None
  loup-pere: None
  mechant-loup: None
  loup-blanc: None
  voyante: None
  sorciere: None
  ange: None
  villageois-1: None
  villageois-2: None
  villageois-3: None
  villageois-4: None
  villageois-5: None
  villageois-6: None
  villageois-7: None

game:
  target-loups:
